/* Reader-facing stylesheet for exported/preview pages. Static string (palette + fonts
   come from CSS vars injected by docShell). Mirrors the editor layouts, read-only. */

export const READER_CSS = [
"*{box-sizing:border-box}",
"body{margin:0;min-height:100vh;background:var(--bg);color:var(--ink);font-family:var(--sans);font-size:15px;-webkit-font-smoothing:antialiased}",
"a{color:var(--accent-soft);text-decoration:none}a:hover{text-decoration:underline}",
"a.xref{color:var(--accent);font-weight:500;border-bottom:1px solid color-mix(in srgb,var(--accent) 32%,transparent)}",
"a.xref:hover{border-bottom-color:var(--accent);text-decoration:none}",
".xref.dead{color:var(--muted);border-bottom:1px dotted var(--faint)}",
"ul,ol{margin:.55em 0;padding-left:1.5em}",
"li{margin:.28em 0;line-height:1.6}",
".navtree li,.bllist li{margin:0;line-height:1.3}",
".embeds{display:flex;flex-direction:column;gap:14px;margin:8px 0}",
".spembed{border:0;border-radius:12px;width:100%;display:block;max-width:640px}",
".empty{color:var(--faint);font-style:italic}",

/* topbar */
".topbar{position:sticky;top:0;z-index:10;display:flex;align-items:center;gap:16px;padding:12px 26px;background:var(--panel);border-bottom:1px solid var(--rule)}",
".topbar .crumb{font-family:var(--mono);font-size:.66rem;letter-spacing:.1em;text-transform:uppercase;color:var(--faint)}.topbar .crumb a{color:var(--accent)}",
".topbar .tbadge{margin-left:auto;font-family:var(--mono);font-size:.56rem;letter-spacing:.14em;text-transform:uppercase;color:var(--accent-soft);border:1px solid var(--rule);border-radius:20px;padding:3px 10px}",

/* titles */
".etitle h1{font-family:var(--head);font-weight:400;font-size:calc(2.4rem*var(--hs,1));line-height:1.03;margin:0;color:var(--ink);text-wrap:balance}",
".esub{font-family:var(--mono);font-size:.66rem;letter-spacing:.16em;text-transform:uppercase;color:var(--accent);margin-top:8px}",
".words{display:flex;align-items:center;gap:12px;margin-top:8px}.words::before,.words::after{content:'';height:1px;flex:1;max-width:90px;background:var(--rule)}.words span{font-family:var(--body);font-style:italic;color:var(--muted)}",
".whero .etitle,.whero .words{align-items:center;text-align:center}.whero .etitle h1{text-align:center}.whero .esub{text-align:center}.whero .words{justify-content:center}",

/* layout containers */
".wrap-narrow{max-width:760px;margin:0 auto;padding:34px 26px 90px}",
".whero{max-width:900px;margin:0 auto;padding:34px 26px 90px}",
".herohead{display:flex;gap:20px;align-items:center}.herohead .sig{flex:none;width:104px}",
".wsplit{max-width:1160px;margin:0 auto;padding:34px 30px 90px;display:grid;grid-template-columns:minmax(180px,calc(340px * var(--ps,1))) 1fr;gap:40px;align-items:start}",
".wsplit .media{position:sticky;top:70px}",
".wbody{display:grid;grid-template-columns:1fr 300px;max-width:1160px;margin:0 auto;gap:40px;padding:0 26px}",
".wbody .article{padding:34px 0;min-width:0}.wbody .infobox{padding:34px 0}",

/* headings + prose */
"h2{font-family:var(--head);font-weight:400;font-size:calc(1.7rem*var(--hs,1));color:var(--ink);margin:34px 0 12px;padding-bottom:8px;border-bottom:1px solid var(--rule)}",
"h3{font-size:.72rem;letter-spacing:.14em;text-transform:uppercase;color:var(--accent);margin:22px 0 8px}",
"h4{font-size:.66rem;font-weight:700;letter-spacing:.14em;text-transform:uppercase;color:var(--faint);margin:0 0 10px;padding-bottom:6px;border-bottom:1px solid var(--line)}",
"p{font-family:var(--body);font-size:calc(1rem*var(--bs,1));line-height:1.72;color:var(--ink);opacity:.92;margin:0 0 14px}",
".lead{font-family:var(--body);font-size:calc(1.14rem*var(--bs,1));line-height:1.7;color:var(--ink);border-left:3px solid var(--accent);padding-left:16px;margin:14px 0 24px}",

/* stats */
".stats{border:1px solid var(--rule);border-radius:8px;overflow:hidden;margin:6px 0}",
".stats .r{display:grid;grid-template-columns:40% 1fr;gap:8px;padding:8px 12px;border-bottom:1px solid var(--line);font-size:.82rem}.stats .r:last-child{border-bottom:none}",
".stats .k{font-family:var(--mono);font-size:.58rem;letter-spacing:.06em;text-transform:uppercase;color:var(--faint)}.stats .v{color:var(--muted);font-family:var(--body)}",

/* carousel */
".carousel{border:1px solid var(--rule);border-radius:12px;overflow:hidden;background:var(--panel-2);margin:6px 0}",
".cstage{position:relative;aspect-ratio:16/10}.cslide{position:absolute;inset:0;display:none}.cslide.on{display:block}.cslide img{width:100%;height:100%;object-fit:cover;display:block}",
".herohead .sig .carousel .cstage{aspect-ratio:1}",
".wsplit .media .cstage,.wbody .infobox .cstage{aspect-ratio:3/4}",
".cnav{display:flex;align-items:center;justify-content:space-between;padding:7px 10px;border-top:1px solid var(--rule);background:var(--panel)}",
".cbtn{background:none;border:1px solid var(--rule);border-radius:5px;color:var(--muted);width:30px;height:26px;cursor:pointer;font-size:1rem}.cbtn:hover{color:var(--ink);border-color:var(--accent)}",
".ccount{font-family:var(--mono);font-size:.6rem;letter-spacing:.1em;color:var(--faint)}",

/* relations — one collapsible card with a big 3/4 side portrait (matches editor) */
".rels{display:flex;flex-direction:column;gap:10px;margin-top:6px}",
".rel{border:1px solid var(--rule);border-radius:10px;background:var(--panel);overflow:hidden}",
".rel>summary{list-style:none;cursor:pointer;display:grid;grid-template-columns:48px 1fr auto;gap:14px;align-items:center;padding:10px 14px}.rel>summary::-webkit-details-marker{display:none}.rel>summary:hover{background:var(--line)}",
".rel .rthumb{width:48px;height:60px;border-radius:6px;background:var(--panel-2) center/cover;border:1px solid var(--rule)}",
".rel .rnm{font-family:var(--head);font-size:calc(1.2rem*var(--hs,1));color:var(--ink);display:block;line-height:1.1}",
".rel .rmeta{font-family:var(--mono);font-size:.56rem;letter-spacing:.14em;text-transform:uppercase;color:var(--accent-soft);margin-top:5px;display:block}",
".rel .chev{font-family:var(--mono);color:var(--faint)}.rel .chev::after{content:'▸'}.rel[open] .chev{transform:rotate(90deg)}",
".rel[open]>summary{border-bottom:1px solid var(--rule)}",
".rbody{display:grid;grid-template-columns:180px 1fr;gap:20px;align-items:start;padding:16px}.rbody .rport{width:100%;aspect-ratio:3/4;background:var(--panel-2) center/cover;border:1px solid var(--rule);border-radius:9px}",
".rbody .rtxt p{font-size:calc(.98rem*var(--bs,1))}",
"@media(max-width:640px){.rbody{grid-template-columns:1fr}}",

/* tag groups */
".tcat{margin:0 0 18px}.chips{display:flex;flex-wrap:wrap;gap:8px}",
".chip{border:1px solid var(--rule);border-radius:16px;background:var(--panel);color:var(--ink)}",
".chip.static{padding:6px 14px;font-size:.8rem}",
"details.chip>summary{list-style:none;cursor:pointer;padding:6px 14px;font-size:.8rem;display:flex;gap:8px;align-items:center}details.chip>summary::-webkit-details-marker{display:none}details.chip>summary::after{content:'＋';color:var(--accent-soft)}details.chip[open]>summary::after{content:'−'}",
"details.chip .note{display:block;padding:2px 14px 10px;font-size:.8rem;color:var(--muted);max-width:440px;line-height:1.55}",
"details.chip .note p{margin:0 0 6px}details.chip .note p:last-child{margin:0}",
"details.chip .note ul,details.chip .note ol{margin:4px 0 6px;padding-left:18px}",

/* field-guide catalog */
".fggroup{margin:10px 0 22px}",
".fggh{font-family:var(--mono);font-size:.64rem;letter-spacing:.16em;text-transform:uppercase;color:var(--muted);border-bottom:1px solid var(--rule);padding-bottom:7px;margin:0 0 14px;display:flex;align-items:center;gap:8px}",
".fggh .fgct{color:var(--faint)}",
".fggrid{display:grid;grid-template-columns:repeat(auto-fill,minmax(240px,1fr));gap:15px}",
".fgc{display:flex;flex-direction:column;background:var(--panel);border:1px solid var(--rule);border-radius:12px;overflow:hidden}",
".fgc:hover{border-color:var(--accent)}",
".fgthumb{height:116px;background:var(--panel-2) center/cover no-repeat;border-bottom:1px solid var(--rule)}",
".fgbody{display:flex;flex-direction:column;gap:5px;padding:11px 13px 13px}",
".fgtop{display:flex;align-items:flex-start;justify-content:space-between;gap:8px}",
".fgname{font-family:var(--head);font-size:calc(1.1rem*var(--hs,1));color:var(--ink);line-height:1.12}",
".fgname a{color:var(--ink)}.fgname a:hover{color:var(--accent)}",
".fgkind{font-family:var(--mono);font-size:.56rem;letter-spacing:.1em;text-transform:uppercase;color:var(--faint)}",
".fgdesc{font-size:.86rem;line-height:1.5;color:var(--muted)}",
".fgdesc p{margin:0 0 6px}.fgdesc p:last-child{margin:0}",
".fglink{font-family:var(--mono);font-size:.6rem;letter-spacing:.06em;color:var(--accent);text-decoration:none;align-self:flex-start;margin-top:2px}",
".fglink:hover{text-decoration:underline}",
".fgbadge{display:inline-flex;align-items:center;gap:6px;flex:none;white-space:nowrap}",
".fgbadge .pips{display:inline-flex;gap:2px}",
".fgbadge .pip{width:6px;height:6px;border-radius:50%;border:1px solid var(--bc)}",
".fgbadge .pip.on{background:var(--bc)}",
".fgbadge .blabel{font-family:var(--mono);font-size:.56rem;letter-spacing:.08em;text-transform:uppercase;color:var(--bc)}",

/* header scale meter */
".meter{display:flex;align-items:center;gap:14px;margin:2px 0 14px;flex-wrap:wrap}",
".meter .mlabel{font-family:var(--mono);font-size:.6rem;letter-spacing:.14em;text-transform:uppercase;color:var(--faint)}",
".meter .mcells{display:flex;border:1px solid var(--rule);border-radius:7px;overflow:hidden}",
".meter .mcell{font-family:var(--mono);font-size:.6rem;letter-spacing:.06em;text-transform:uppercase;padding:6px 13px;color:var(--faint);border-right:1px solid var(--rule)}",
".meter .mcell:last-child{border-right:none}",
".meter .mcell.below{color:var(--muted)}",
".meter .mcell.on{background:var(--accent);color:#fff;font-weight:600}",

/* family tree (auto-laid-out genealogy chart) */
".famwrap{overflow-x:auto;margin:8px 0 14px}",
".fam{width:100%;height:auto;display:block;margin:0 auto}",
".fam .fwire{fill:none;stroke:var(--rule);stroke-width:2}",
".fam .fmarr{fill:none;stroke:var(--accent);stroke-width:2.5}",
".fam .fmarr.affair{stroke-dasharray:4 4;opacity:.7}",
".fam .fmlbl{fill:var(--faint);font-family:var(--mono);font-size:8px;letter-spacing:1px;text-anchor:middle;text-transform:uppercase}",
".fam .fnode rect{fill:var(--panel);stroke:var(--rule);stroke-width:1.5}",
".fam a{cursor:pointer}.fam a:hover .fnode rect{stroke:var(--accent)}",
".fam .fnm{fill:var(--ink);font-family:var(--head);font-size:15px;text-anchor:middle}",
".fam .fsur{fill:var(--muted);font-family:var(--head);font-size:12.5px;text-anchor:middle}",

/* full-width bands (below codex columns) */
".bands{max-width:1140px;margin:14px auto 0;padding:0 34px}",

/* codex rail widgets (species) */
".codexrail .railw{margin-bottom:18px}",
".codexrail .rwh{font-family:var(--mono);font-size:.58rem;letter-spacing:.12em;text-transform:uppercase;color:var(--faint);margin:0 0 8px;padding-bottom:6px;border-bottom:1px solid var(--rule)}",

/* place Kind chip + At-a-glance gauges */
".kindchip{display:flex;align-items:center;gap:8px;flex-wrap:wrap}",
".kindchip .klabel{font-family:var(--head);font-size:1.05rem;color:var(--ink)}",
".kindchip .kgenre{font-family:var(--mono);font-size:.5rem;letter-spacing:.1em;text-transform:uppercase;color:var(--accent);border:1px solid color-mix(in srgb,var(--accent) 40%,var(--rule));border-radius:20px;padding:2px 7px}",
".gauges{display:grid;grid-template-columns:1fr 1fr;gap:8px}",
".gtile{background:var(--panel-2,rgba(255,255,255,.03));border:1px solid var(--rule);border-radius:9px;padding:8px 10px}",
".gtile .gl{font-family:var(--mono);font-size:.5rem;letter-spacing:.09em;text-transform:uppercase;color:var(--faint)}",
".gtile .gv{font-family:var(--head);font-size:1rem;color:var(--ink);margin-top:3px}",
".gtile .gpips{display:flex;gap:3px;margin-top:6px}",
".gtile .gpip{flex:1;height:5px;border-radius:3px;background:var(--rule)}",
".gtile .gpip.on{background:var(--accent)}",
".gtile .gnow{font-family:var(--head);font-size:.92rem;color:var(--ink);margin-top:5px}",

/* standalone Timeline — Chronicle spine */
".tline{margin:6px 0 4px}",
".tera{display:flex;align-items:center;gap:12px;margin:22px 0 12px}",
".tera:first-child{margin-top:4px}",
".tera .ten{font-family:var(--mono);font-size:.64rem;letter-spacing:.16em;text-transform:uppercase;color:var(--accent);white-space:nowrap}",
".tera .tespan{font-family:var(--mono);font-size:.56rem;letter-spacing:.06em;color:var(--faint)}",
".tera .tel{flex:1;height:1px;background:linear-gradient(90deg,color-mix(in srgb,var(--accent) 45%,transparent),transparent)}",
".tspine{position:relative;padding-left:118px}",
".tspine::before{content:'';position:absolute;left:98px;top:6px;bottom:6px;width:1px;background:var(--rule)}",
".tlnode{position:relative;margin-bottom:6px}",
".tlnode>summary{list-style:none;cursor:pointer;display:flex;align-items:flex-start;gap:10px;padding:7px 8px 7px 0;border-radius:8px}",
".tlnode>summary::-webkit-details-marker{display:none}",
".tlnode>summary:hover{background:color-mix(in srgb,var(--accent) 6%,transparent)}",
".tlnode .tldate{position:absolute;left:-118px;top:9px;width:86px;text-align:right;font-family:var(--mono);font-size:.62rem;color:var(--accent-soft);line-height:1.35}",
".tlnode::before{content:'';position:absolute;left:-24px;top:12px;width:9px;height:9px;border-radius:50%;background:var(--bg,#12151a);border:2px solid var(--faint);z-index:1}",
".tlnode.key::before{background:var(--accent);border-color:var(--accent);box-shadow:0 0 0 4px color-mix(in srgb,var(--accent) 16%,transparent)}",
".tlnode .tltitle{font-family:var(--head);font-size:calc(1.12rem*var(--bs,1));color:var(--ink);line-height:1.25;flex:1}",
".tlnode .tlstar{color:var(--accent);font-size:.68rem;flex:0 0 auto;margin-top:3px}",
".tlnode .chev{font-family:var(--mono);color:var(--faint);flex:0 0 auto;margin-top:2px}.tlnode .chev::after{content:'▸'}.tlnode[open] .chev{transform:rotate(90deg)}",
".tlbody{padding:2px 8px 12px 8px;color:var(--muted)}",
".tlbody p{margin:0 0 8px}.tlbody p:last-child{margin:0}",
".tllinks{display:flex;flex-direction:column;gap:8px;margin-top:10px}",
/* Level-2 inline link preview */
".tlink{border:1px solid var(--rule);border-radius:10px;background:var(--panel-2,rgba(255,255,255,.02));overflow:hidden}",
".tlink>summary{list-style:none;cursor:pointer;padding:6px 10px;display:flex;align-items:center;gap:8px}.tlink>summary::-webkit-details-marker{display:none}",
".tlink>summary::after{content:'▸';font-family:var(--mono);color:var(--faint);margin-left:auto}.tlink[open]>summary::after{content:'▾'}",
".tlink .tlchip{font-family:var(--mono);font-size:.62rem;letter-spacing:.02em;color:var(--accent-soft)}",
".tlcard{display:flex;gap:12px;padding:0 12px 12px;align-items:flex-start}",
".tlcov{width:52px;height:52px;flex:0 0 52px;border-radius:8px;background-size:cover;background-position:center;border:1px solid var(--rule)}",
".tlcov.empty{display:flex;align-items:center;justify-content:center;color:var(--faint)}",
".tlm{flex:1;min-width:0}",
".tltype{font-family:var(--mono);font-size:.5rem;letter-spacing:.1em;text-transform:uppercase;color:var(--faint)}",
".tlname{font-family:var(--head);font-size:1.05rem;color:var(--ink);margin:1px 0 2px}.tlname a{color:var(--ink)}.tlname a:hover{color:var(--accent)}",
".tlsum{color:var(--muted);font-size:.86rem;line-height:1.4}",
".tlopen{font-family:var(--mono);font-size:.56rem;letter-spacing:.04em;color:var(--accent-soft);text-decoration:none;white-space:nowrap;flex:0 0 auto}",
/* B · Tracks (swimlanes) */
".ttracks{display:grid;border:1px solid var(--line);border-radius:12px;overflow:hidden;margin:6px 0 4px}",
".ttracks .tlh{padding:9px 12px;font-family:var(--mono);font-size:.6rem;letter-spacing:.06em;text-transform:uppercase;border-bottom:1px solid var(--rule);background:var(--panel-2,rgba(255,255,255,.03))}",
".ttracks .tlh.time{color:var(--faint)}",
".ttracks .tcell{border-bottom:1px solid var(--line);padding:9px;min-height:48px}",
".ttracks .tcell.time{font-family:var(--mono);font-size:.6rem;color:var(--accent-soft);background:var(--panel-2,rgba(255,255,255,.03));text-align:right;border-right:1px solid var(--rule);padding-top:11px}",
".ttracks .tev{border:1px solid color-mix(in srgb,var(--tc) 32%,var(--rule));background:color-mix(in srgb,var(--tc) 12%,transparent);border-radius:8px;padding:7px 9px}",
".ttracks .tev+.tev{margin-top:6px}",
".ttracks .tevt{font-family:var(--head);font-size:calc(.98rem*var(--bs,1));color:var(--ink)}",
".ttracks .tevstar{color:var(--accent);font-size:.62rem;vertical-align:super;margin-left:4px}",
".ttracks .tevb{color:var(--muted);font-size:.82rem;margin-top:2px}",
".ttracks .tevlk{display:flex;flex-wrap:wrap;gap:5px;margin-top:6px}",
".tchip{font-family:var(--mono);font-size:.54rem;letter-spacing:.02em;color:var(--accent-soft);border:1px solid var(--rule);border-radius:5px;padding:2px 7px;text-decoration:none}",
"a.tchip:hover{border-color:var(--accent)}",
/* C · Era ledger */
".tledger{margin:6px 0 4px}",
".tlg{margin-bottom:22px}",
".tlgh{display:flex;align-items:baseline;gap:12px;padding-bottom:7px;margin-bottom:2px;border-bottom:1px solid var(--rule)}",
".tlgh .tlgn{font-family:var(--head);font-size:1.22rem;color:var(--ink)}",
".tlgh .tlgspan{font-family:var(--mono);font-size:.58rem;color:var(--faint)}",
".tlgh .tlgc{margin-left:auto;font-family:var(--mono);font-size:.56rem;color:var(--faint)}",
".tlcolhead{display:grid;grid-template-columns:92px 1fr 170px 62px;gap:14px;padding:0 6px 6px;font-family:var(--mono);font-size:.52rem;letter-spacing:.1em;text-transform:uppercase;color:var(--faint)}",
".tlcolhead .r{text-align:right}",
".tlrow{display:grid;grid-template-columns:92px 1fr 170px 62px;gap:14px;align-items:center;padding:8px 6px;border-bottom:1px solid var(--line)}",
".tlrow .tld{font-family:var(--mono);font-size:.62rem;color:var(--accent-soft)}",
".tlrow .tle{color:var(--ink);font-size:.95rem}",
".tlrow .tlestar{color:var(--accent);font-size:.6rem;vertical-align:super}",
".tlrow .tlw{display:flex;flex-wrap:wrap;gap:5px}",
".tlrow .tlsig{text-align:right;letter-spacing:2px;font-size:.7rem}",
".tlrow .tlsig .on{color:var(--accent)}.tlrow .tlsig .off{color:var(--rule)}",

/* Character arc line */
".arcbox{display:flex;flex-direction:column;gap:12px;margin:6px 0 4px}",
".arcchart{position:relative;border:1px solid var(--line);border-radius:12px;background:var(--panel-2,rgba(255,255,255,.02));padding:6px 8px 2px}",
".arcchart .aax{position:absolute;font-family:var(--mono);font-size:.5rem;letter-spacing:.1em;text-transform:uppercase;pointer-events:none}",
".arcchart .aax.top{top:10px;left:14px;color:#5aa06f}.arcchart .aax.bot{bottom:34px;left:14px;color:#b0596a}",
"svg.arccurve{width:100%;height:auto;display:block}",
".acaps{display:grid;grid-template-columns:1fr 1fr 1fr;gap:10px}",
".acap{border:1px solid var(--line);border-radius:10px;background:var(--panel);padding:10px 12px}",
".acap.start{border-top:2px solid var(--ac,#b0596a)}.acap.turn{border-top:2px solid var(--accent)}.acap.end{border-top:2px solid var(--ac,#5aa06f)}",
".acap .acph{font-family:var(--mono);font-size:.52rem;letter-spacing:.1em;text-transform:uppercase;color:var(--faint);margin-bottom:8px}",
".arow{margin-bottom:6px}.arow:last-child{margin-bottom:0}",
".arow .ak{font-family:var(--mono);font-size:.48rem;letter-spacing:.06em;text-transform:uppercase;color:var(--faint)}",
".arow .av{font-size:.9rem;color:var(--ink);line-height:1.3;margin-top:1px}",
".arow .av.lie{color:#b0596a}.arow .av.truth{color:#5aa06f}",
".aforces{display:grid;grid-template-columns:1fr 1fr;gap:10px}",
".aforce{border:1px solid var(--line);border-radius:11px;background:var(--panel);padding:11px 13px}",
".aforce.want{border-left:3px solid #c99a5a}.aforce.need{border-left:3px solid #5f9fb0}",
".aforce .afk{font-family:var(--mono);font-size:.54rem;letter-spacing:.06em;text-transform:uppercase;margin-bottom:5px}",
".aforce.want .afk{color:#c99a5a}.aforce.need .afk{color:#5f9fb0}",
".aforce .afv{font-size:.98rem;color:var(--ink)}",
".aforce .afx{font-size:.76rem;color:var(--faint);margin-top:3px}",
"@media(max-width:640px){.acaps,.aforces{grid-template-columns:1fr}}",

/* system rules — numbered laws + Can/Can't */
".rlaws{counter-reset:law;list-style:none;margin:6px 0;padding:0}",
".rlaws li{counter-increment:law;position:relative;padding:8px 0 8px 34px;border-bottom:1px solid var(--line);color:var(--ink);font-size:.96rem}",
".rlaws li:last-child{border-bottom:none}",
".rlaws li::before{content:counter(law);position:absolute;left:0;top:7px;width:22px;height:22px;border-radius:50%;border:1px solid color-mix(in srgb,var(--accent) 45%,var(--rule));color:var(--accent-soft);font-family:var(--mono);font-size:.7rem;display:flex;align-items:center;justify-content:center}",
".rcancant{display:grid;grid-template-columns:1fr 1fr;gap:0;border:1px solid var(--rule);border-radius:12px;overflow:hidden;margin:6px 0}",
".rcc{padding:12px 15px}.rcc.can{border-right:1px solid var(--rule)}",
".rcc .rcch{font-family:var(--mono);font-size:.56rem;letter-spacing:.08em;text-transform:uppercase;margin-bottom:8px}",
".rcc.can .rcch{color:#5aa06f}.rcc.cant .rcch{color:#b0596a}",
".rcc ul{margin:0;padding-left:16px;font-size:.9rem;color:var(--ink)}.rcc li{margin:4px 0}",
".rcc.can li::marker{color:#5aa06f}.rcc.cant li::marker{color:#b0596a}",
"@media(max-width:600px){.rcancant{grid-template-columns:1fr}.rcc.can{border-right:none;border-bottom:1px solid var(--rule)}}",

/* relationship dyad */
".dyad{display:flex;flex-direction:column;gap:14px;margin:6px 0 4px}",
".dhead{display:grid;grid-template-columns:1fr auto 1fr;gap:14px;align-items:center}",
".dwho{display:flex;align-items:center;gap:11px;min-width:0}",
".dwho.b{flex-direction:row-reverse;text-align:right}",
".dav{width:52px;height:52px;border-radius:50%;flex:0 0 auto;background:var(--panel-2) center/cover;border:2px solid var(--rule);display:flex;align-items:center;justify-content:center;font-family:var(--head);font-size:1.2rem;color:var(--muted)}",
".dwho.a .dav{border-color:color-mix(in srgb,#c99a5a 60%,var(--rule))}.dwho.b .dav{border-color:color-mix(in srgb,#5f9fb0 60%,var(--rule))}",
".dwm{min-width:0}",
".dnm{font-family:var(--head);font-size:1.14rem;color:var(--ink);display:block;line-height:1.1}.dnm a{color:var(--ink)}.dnm a:hover{color:var(--accent)}",
".drl{font-family:var(--mono);font-size:.52rem;letter-spacing:.08em;text-transform:uppercase;color:var(--faint)}",
".dwho.a .drl{color:#c99a5a}.dwho.b .drl{color:#5f9fb0}",
".dbond{display:flex;flex-direction:column;align-items:center;gap:5px}",
".dbond .dlink{font-size:1.2rem;color:var(--accent-soft)}",
".dbond .ddyn{font-family:var(--mono);font-size:.54rem;letter-spacing:.06em;text-transform:uppercase;color:var(--accent);border:1px solid color-mix(in srgb,var(--accent) 40%,var(--rule));border-radius:20px;padding:3px 10px;white-space:nowrap}",
".dbond .dstatus{font-family:var(--mono);font-size:.5rem;letter-spacing:.05em;text-transform:uppercase;color:var(--faint)}",
".dtension{border:1px solid color-mix(in srgb,var(--accent) 28%,var(--rule));border-radius:11px;background:color-mix(in srgb,var(--accent) 6%,transparent);padding:11px 14px}",
".dtension .dtl{font-family:var(--mono);font-size:.52rem;letter-spacing:.1em;text-transform:uppercase;color:var(--accent-soft);margin-bottom:3px}",
".dtension p{margin:0;color:var(--ink);font-size:1rem}",
".dsides{display:grid;grid-template-columns:1fr 1fr;gap:12px}",
".dside{border:1px solid var(--rule);border-radius:11px;background:var(--panel-2,rgba(255,255,255,.02));padding:12px 14px}",
".dside.a{border-top:2px solid #c99a5a}.dside.b{border-top:2px solid #5f9fb0}",
".dside .dsh{font-family:var(--head);font-size:1.02rem;color:var(--ink);margin-bottom:9px}",
".dside .dsh span{font-family:var(--mono);font-size:.5rem;letter-spacing:.06em;text-transform:uppercase;color:var(--faint);margin-left:6px}",
".dside .drow{margin-bottom:7px}.dside .drow:last-child{margin-bottom:0}",
".dside .dk{font-family:var(--mono);font-size:.5rem;letter-spacing:.06em;text-transform:uppercase;color:var(--faint)}",
".dside .dv{font-size:.92rem;color:var(--ink);margin-top:1px}",
"@media(max-width:600px){.dhead{grid-template-columns:1fr}.dwho.b{flex-direction:row;text-align:left}.dsides{grid-template-columns:1fr}}",

/* org / hierarchy chart */
".orgchart{overflow-x:auto;border:1px solid var(--rule);border-radius:12px;background:var(--panel-2,rgba(255,255,255,.02));padding:16px;margin:6px 0 4px}",
".orgchart a{text-decoration:none}",
".orgchart a:hover rect{stroke:var(--accent)}",
/* stat chart — radar / bars */
".statchart{margin:8px 0 4px;display:flex;justify-content:center}",
".scradar{width:min(300px,100%);height:auto}",
".scbars{width:100%;max-width:520px;display:flex;flex-direction:column;gap:7px}",
".scbar{display:grid;grid-template-columns:6em 1fr 2.6em;gap:10px;align-items:center}",
".scbar .scl{font-family:var(--mono);font-size:.58rem;letter-spacing:.05em;text-transform:uppercase;color:var(--muted);text-align:right}",
".scbar .sct{height:9px;border-radius:5px;background:var(--rule);overflow:hidden}",
".scbar .sct i{display:block;height:100%;background:var(--accent);border-radius:5px}",
".scbar .scv{font-family:var(--mono);font-size:.74rem;color:var(--ink)}",
/* relationship matrix */
".matrix{margin:6px 0 4px}",
".mtxscroll{overflow:auto;border:1px solid var(--rule);border-radius:10px}",
".mtx{border-collapse:collapse}",
".mtx th,.mtx td{border:1px solid var(--line)}",
".mtx .mcorner{background:var(--panel-2,rgba(255,255,255,.03))}",
".mtx .mcol{background:var(--panel-2,rgba(255,255,255,.03));vertical-align:bottom;height:104px;padding:6px 4px}",
".mtx .mcol span{writing-mode:vertical-rl;transform:rotate(200grad);display:inline-block;font-family:var(--mono);font-size:.6rem;letter-spacing:.04em;color:var(--muted);white-space:nowrap;max-height:94px;overflow:hidden;text-overflow:ellipsis}",
".mtx .mrow{background:var(--panel-2,rgba(255,255,255,.03));text-align:right;padding:0 10px;font-size:.86rem;color:var(--ink);white-space:nowrap;max-width:160px;overflow:hidden;text-overflow:ellipsis;position:sticky;left:0}",
".mtx .mself{min-width:34px;background:repeating-linear-gradient(45deg,var(--panel-2,#1c2228),var(--panel-2,#1c2228) 5px,transparent 5px,transparent 10px)}",
".mtx .mcell{min-width:34px;height:34px}",
".mlegend{display:flex;flex-wrap:wrap;gap:12px;margin-top:9px}",
".mlegend .mlg{display:inline-flex;align-items:center;gap:6px;font-family:var(--mono);font-size:.58rem;letter-spacing:.04em;text-transform:uppercase;color:var(--muted)}",
".mlegend .mlg i{width:12px;height:12px;border-radius:3px}",
/* safe embeds (video / map / 3D) */
".embeds{display:flex;flex-direction:column;gap:14px;margin:6px 0 4px}",
".embed .emframe{position:relative;width:100%;border:1px solid var(--rule);border-radius:10px;overflow:hidden;background:#000}",
".embed .emframe iframe{position:absolute;inset:0;width:100%;height:100%;border:0}",
".embed .emcap{font-family:var(--mono);font-size:.62rem;letter-spacing:.02em;color:var(--faint);margin-top:6px}",
".embed>a{color:var(--accent-soft);word-break:break-all}",
/* generic table */
".dtblwrap{overflow-x:auto;border:1px solid var(--rule);border-radius:10px;margin:6px 0 4px}",
".dtbl{border-collapse:collapse;width:100%;font-size:.9rem}",
".dtbl th{font-family:var(--mono);font-size:.56rem;letter-spacing:.06em;text-transform:uppercase;color:var(--muted);font-weight:600;text-align:left;padding:8px 11px;background:var(--panel-2,rgba(255,255,255,.03));border-bottom:1px solid var(--rule);border-right:1px solid var(--line)}",
".dtbl td{padding:8px 11px;color:var(--ink);border-bottom:1px solid var(--line);border-right:1px solid var(--line);vertical-align:top}",
".dtbl th:last-child,.dtbl td:last-child{border-right:none}",
".dtbl tbody tr:last-child td{border-bottom:none}",
".dtbl tbody tr:hover td{background:color-mix(in srgb,var(--accent) 5%,transparent)}",
/* two-column dialectic (Theme statement↔counter, Setting then→now) */
".dialecticbox{display:grid;grid-template-columns:1fr 40px 1fr;gap:0;align-items:stretch;margin:6px 0 4px}",
".dialecticbox .dside{border:1px solid var(--rule);border-radius:12px;border-top:2px solid var(--dt);background:var(--panel-2,rgba(255,255,255,.02));padding:12px 15px}",
".dialecticbox .dsh{font-family:var(--mono);font-size:.54rem;letter-spacing:.08em;text-transform:uppercase;color:var(--dt);margin-bottom:7px}",
".dialecticbox .dside p{margin:0;color:var(--ink);font-size:.98rem;line-height:1.5}",
".dialecticbox .dvs{display:flex;align-items:center;justify-content:center;font-family:var(--mono);color:var(--faint)}",
"@media(max-width:600px){.dialecticbox{grid-template-columns:1fr}.dialecticbox .dvs{padding:6px 0}}",
/* operation — crew roster with portraits */
".crewgrid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:6px 0 4px}",
".crewgrid .op{display:grid;grid-template-columns:74px 1fr;gap:13px;border:1px solid var(--rule);border-radius:13px;background:var(--panel-2,rgba(255,255,255,.02));padding:12px;position:relative}",
".crewgrid .op.wild{border-color:color-mix(in srgb,#b0413a 35%,var(--rule))}",
".crewgrid .oport{width:74px;height:92px;border-radius:9px;border:1px solid var(--rule);background:var(--panel) center/cover;display:flex;align-items:center;justify-content:center;font-family:var(--head);font-size:1.6rem;color:var(--faint)}",
".crewgrid .opm{min-width:0}",
".crewgrid .optop{display:flex;align-items:baseline;gap:8px;flex-wrap:wrap}",
".crewgrid .onm{font-family:var(--head);font-size:1.16rem;color:var(--ink)}.crewgrid .onm a{color:var(--ink)}.crewgrid .onm a:hover{color:var(--accent)}",
".crewgrid .orole{font-family:var(--mono);font-size:.5rem;letter-spacing:.08em;text-transform:uppercase;color:#6f8296;border:1px solid color-mix(in srgb,#6f8296 40%,var(--rule));border-radius:20px;padding:2px 7px}",
".crewgrid .orows{margin-top:8px;display:flex;flex-direction:column;gap:5px}",
".crewgrid .orow{font-size:.86rem;line-height:1.35}",
".crewgrid .ok{font-family:var(--mono);font-size:.46rem;letter-spacing:.06em;text-transform:uppercase;color:var(--faint);margin-right:6px}",
".crewgrid .ov{color:var(--ink)}",
".crewgrid .orow.cover .ov{color:#7fae90}.crewgrid .orow.angle .ov{color:var(--muted);font-style:italic}",
".crewgrid .ostatus{position:absolute;top:12px;right:12px;font-family:var(--mono);font-size:.46rem;letter-spacing:.06em;text-transform:uppercase;border-radius:20px;padding:2px 7px}",
".crewgrid .ostatus.in{color:#5aa06f;border:1px solid color-mix(in srgb,#5aa06f 45%,var(--rule))}",
".crewgrid .ostatus.wildcard{color:#b0413a;border:1px solid color-mix(in srgb,#b0413a 45%,var(--rule))}",
".crewgrid .ostatus.burned{color:#c9704a;border:1px solid color-mix(in srgb,#c9704a 45%,var(--rule))}",
".crewgrid .ostatus.lost{color:var(--faint);border:1px solid var(--rule)}",
"@media(max-width:600px){.crewgrid{grid-template-columns:1fr}}",
/* case — suspects grid */
".suspwrap{overflow-x:auto;border:1px solid var(--rule);border-radius:11px;margin:6px 0 4px}",
".susptbl{border-collapse:collapse;width:100%;min-width:720px;font-size:.88rem}",
".susptbl th{font-family:var(--mono);font-size:.52rem;letter-spacing:.06em;text-transform:uppercase;color:var(--faint);font-weight:600;text-align:left;padding:9px 11px;border-bottom:1px solid var(--rule);background:var(--panel-2,rgba(255,255,255,.03))}",
".susptbl td{padding:10px 11px;border-bottom:1px solid var(--line);vertical-align:top;color:var(--muted)}",
".susptbl tr:last-child td{border-bottom:none}",
".susptbl td.sn{color:var(--ink);white-space:nowrap}.susptbl td.sn a{color:var(--ink)}.susptbl td.sn a:hover{color:var(--accent)}",
".susptbl .astat{font-family:var(--mono);font-size:.48rem;letter-spacing:.05em;text-transform:uppercase;border-radius:20px;padding:1px 7px;white-space:nowrap;margin-left:4px}",
".susptbl .astat.ok{color:#5aa06f;border:1px solid color-mix(in srgb,#5aa06f 45%,var(--rule))}",
".susptbl .astat.unc{color:#c9a24a;border:1px solid color-mix(in srgb,#c9a24a 45%,var(--rule))}",
".susptbl .astat.broken{color:#b0413a;border:1px solid color-mix(in srgb,#b0413a 45%,var(--rule))}",
".spips{display:inline-flex;gap:3px}.spips i{width:9px;height:9px;border-radius:50%;background:var(--rule)}.spips i.on{background:var(--accent)}",
/* case — clues */
".cluelist{display:flex;flex-direction:column;gap:9px;margin:6px 0 4px}",
".cluecard{border:1px solid var(--rule);border-left:3px solid #5f9fb0;border-radius:10px;background:var(--panel-2,rgba(255,255,255,.02));padding:11px 14px}",
".cluecard.herring{border-left-color:#8a86c9}",
".cluecard .clt{font-family:var(--head);font-size:1.06rem;color:var(--ink)}.cluecard .clt a{color:var(--ink)}.cluecard .clt a:hover{color:var(--accent)}",
".clg{font-family:var(--mono);font-size:.5rem;letter-spacing:.05em;text-transform:uppercase;color:#5f9fb0;border:1px solid color-mix(in srgb,#5f9fb0 45%,var(--rule));border-radius:20px;padding:2px 8px;white-space:nowrap}",
".clh{font-family:var(--mono);font-size:.5rem;letter-spacing:.05em;text-transform:uppercase;color:#8a86c9;border:1px solid color-mix(in srgb,#8a86c9 45%,var(--rule));border-radius:20px;padding:2px 8px;white-space:nowrap}",
".clfaces{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:8px}",
".clface{border:1px solid var(--line);border-radius:8px;padding:7px 10px;background:var(--panel)}",
".clface .clk{font-family:var(--mono);font-size:.48rem;letter-spacing:.06em;text-transform:uppercase;color:var(--faint)}",
".clface.reads .clk{color:#8a86c9}.clface.means .clk{color:#5f9fb0}",
".clface .clv{font-size:.88rem;color:var(--ink);margin-top:2px}",
".clfoot{display:flex;gap:16px;flex-wrap:wrap;margin-top:8px;font-family:var(--mono);font-size:.54rem;letter-spacing:.04em;text-transform:uppercase;color:var(--faint)}",
".clfoot b{color:var(--accent-soft);font-weight:400}.clfoot a{color:var(--accent-soft)}",
"@media(max-width:560px){.clfaces{grid-template-columns:1fr}}",
/* sealed spoiler (e.g. a Case's solution) */
".sealed{border:1px dashed color-mix(in srgb,#b0413a 50%,var(--rule));border-radius:11px;background:color-mix(in srgb,#b0413a 6%,transparent);margin:16px 0;overflow:hidden}",
".sealed>summary{list-style:none;cursor:pointer;padding:11px 15px;font-family:var(--mono);font-size:.6rem;letter-spacing:.1em;text-transform:uppercase;color:#b0413a}",
".sealed>summary::-webkit-details-marker{display:none}",
".sealed[open]>summary{border-bottom:1px solid color-mix(in srgb,#b0413a 30%,var(--rule))}",
".sealedb{padding:6px 15px 14px}.sealedb h3{margin-top:12px}",

/* history — vertical buildable timeline */
".vtl{position:relative;margin:4px 0 8px;padding-left:24px}",
".vtl::before{content:'';position:absolute;left:5px;top:9px;bottom:9px;width:1px;background:var(--rule)}",
".vtl .vnode{position:relative;padding-bottom:20px}",
".vtl .vnode:last-child{padding-bottom:2px}",
".vtl .vnode::before{content:'';position:absolute;left:-24px;top:5px;width:11px;height:11px;border-radius:50%;background:var(--panel);border:2px solid var(--rule)}",
".vtl .vnode.key::before{background:var(--accent);border-color:var(--accent)}",
".vtl .vdate{font-family:var(--mono);font-size:.58rem;letter-spacing:.1em;text-transform:uppercase;color:var(--accent);margin-bottom:5px}",
".vtl .vb h4{font-family:var(--head);font-weight:500;font-size:calc(1.18rem*var(--hs,1));color:var(--ink);margin:0 0 4px}",
".vtl .vb p{margin:0 0 7px;color:var(--muted)}.vtl .vb p:last-child{margin:0}",

/* ties — relations with other groups */
".tiegrid{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:12px;margin:4px 0 8px}",
".tiegrid .tie{border:1px solid var(--rule);border-left:3px solid var(--tc,var(--rule));border-radius:10px;background:var(--panel);padding:10px 14px;display:flex;flex-direction:column;gap:3px}",
".tiegrid .tg{font-family:var(--head);font-size:calc(1.08rem*var(--hs,1));color:var(--ink)}",
".tiegrid .tg a{color:var(--ink);text-decoration:none}.tiegrid .tg a:hover{color:var(--accent)}",
".tiegrid .tt{font-family:var(--mono);font-size:.54rem;letter-spacing:.1em;text-transform:uppercase;color:var(--tc,var(--muted))}",
".tiegrid .tn{color:var(--muted);font-size:.88rem;line-height:1.45}",

/* zone divider (research zones) */
".zonebar{display:flex;align-items:center;gap:14px;margin:34px 0 16px}",
".zonebar .zt{font-family:var(--mono);font-size:.66rem;letter-spacing:.2em;text-transform:uppercase;color:var(--accent);white-space:nowrap}",
".zonebar .zl{flex:1;height:1px;background:linear-gradient(90deg,var(--accent),transparent);opacity:.5}",

/* lexicon — grouped term cards with usage examples */
".lex{display:flex;flex-direction:column;gap:20px;margin:2px 0 6px}",
".lexcat-h{font-family:var(--mono);font-size:.6rem;letter-spacing:.16em;text-transform:uppercase;color:var(--muted);margin:0 0 12px;padding-bottom:6px;border-bottom:1px solid var(--rule)}",
".lexgrid{display:grid;grid-template-columns:repeat(auto-fill,minmax(240px,1fr));gap:12px}",
".lex .term{border:1px solid var(--rule);border-radius:10px;background:var(--panel);padding:12px 15px}",
".lex .tt{font-family:var(--head);font-size:calc(1.15rem*var(--hs,1));color:var(--ink);display:flex;align-items:baseline;gap:9px;flex-wrap:wrap;line-height:1.15}",
".lex .pron{font-family:var(--mono);font-size:.62rem;color:var(--faint)}",
".lex .td{color:var(--muted);font-size:.94rem;margin-top:5px;line-height:1.5}",
".lex .ex{margin-top:9px;padding-left:11px;border-left:2px solid var(--accent);font-style:italic;color:var(--ink);font-size:.94rem}",
".lex .ex b{display:block;font-style:normal;font-family:var(--mono);font-size:.5rem;letter-spacing:.12em;text-transform:uppercase;color:var(--faint);margin-bottom:3px}",
".lex .ts{font-family:var(--mono);font-size:.52rem;letter-spacing:.06em;text-transform:uppercase;color:var(--faint);margin-top:9px}",

/* phrasebook — phrases grouped by category: phrase · translation · literal gloss · usage */
".phrasebook{display:flex;flex-direction:column;gap:20px;margin:2px 0 6px}",
".pbcat-h{font-family:var(--mono);font-size:.6rem;letter-spacing:.16em;text-transform:uppercase;color:var(--muted);margin:0 0 12px;padding-bottom:6px;border-bottom:1px solid var(--rule)}",
".pbgrid{display:grid;grid-template-columns:repeat(auto-fill,minmax(240px,1fr));gap:12px}",
".phrasebook .phrase{border:1px solid var(--rule);border-radius:10px;background:var(--panel);padding:12px 15px;display:flex;flex-direction:column;gap:6px}",
".phrasebook .phw{font-family:var(--head);font-size:calc(1.22rem*var(--hs,1));color:var(--ink);line-height:1.15}",
".phrasebook .phtr{color:var(--ink);font-size:calc(.98rem*var(--bs,1));line-height:1.45}",
".phrasebook .phlit{font-family:var(--mono);font-size:.72rem;color:var(--muted);line-height:1.4}",
".phrasebook .phlit span{color:var(--faint);text-transform:uppercase;letter-spacing:.08em;font-size:.6rem}",
".phrasebook .phuse{margin-top:1px;padding-top:8px;border-top:1px dashed var(--rule);font-style:italic;color:var(--muted);font-size:.9rem;line-height:1.45}",

/* definition list — glossary / quick facts */
".deflist{display:flex;flex-direction:column;gap:6px;margin:2px 0 6px}",
".deflist .drow{display:grid;grid-template-columns:minmax(0,0.9fr) minmax(0,2fr);gap:16px;align-items:baseline;border-bottom:1px solid var(--rule-soft,var(--rule));padding:8px 2px}",
".deflist dt{font-family:var(--head);font-size:calc(1.02rem*var(--hs,1));color:var(--ink);margin:0}",
".deflist dd{margin:0;font-size:calc(.98rem*var(--bs,1));color:var(--muted);display:flex;flex-wrap:wrap;gap:6px 12px;align-items:baseline}",
".deflist .dnote{font-family:var(--mono);font-size:.56rem;letter-spacing:.06em;text-transform:uppercase;color:var(--faint)}",
"@media(max-width:640px){.deflist .drow{grid-template-columns:1fr;gap:3px}}",
/* ability-score grid (stat block) */
".abil{display:grid;grid-template-columns:repeat(auto-fit,minmax(84px,1fr));gap:8px;margin:2px 0 8px}",
".abil .ab{display:flex;flex-direction:column;align-items:center;gap:3px;border:1px solid var(--rule);border-radius:10px;background:var(--panel);padding:9px 4px 7px}",
".abil .abl{font-family:var(--mono);font-size:.56rem;letter-spacing:.12em;text-transform:uppercase;color:var(--accent);font-weight:600;text-align:center}",
".abil .absc{font-family:var(--head);font-size:calc(1.35rem*var(--hs,1));color:var(--ink)}",
".abil .abmod{font-family:var(--mono);font-size:.72rem;color:var(--muted);border-top:1px solid var(--rule);width:64%;text-align:center;padding-top:4px}",
".abil .dots{display:flex;flex-wrap:wrap;gap:4px;justify-content:center;padding:5px 0 1px}",
".abil .dot{width:13px;height:13px;border-radius:50%;border:1.5px solid var(--muted);box-sizing:border-box}",
".abil .dot.fill{background:var(--accent);border-color:var(--accent)}",
/* roll table */
".rolltable{display:flex;flex-direction:column;gap:9px;margin:4px 0 8px}",
".rolltable .rtrows{display:flex;flex-direction:column;gap:5px}",
".rolltable .rtrow{display:grid;grid-template-columns:64px 1fr;gap:12px;align-items:center;border:1px solid var(--rule);border-radius:8px;background:var(--panel);padding:7px 12px}",
".rolltable .rtrow.hit{border-color:var(--accent);background:color-mix(in srgb,var(--accent) 14%,var(--panel));box-shadow:inset 3px 0 var(--accent)}",
".rolltable .rtrange{font-family:var(--mono);font-size:.8rem;text-align:center;color:var(--muted)}",
".rolltable .rttext{font-size:calc(.98rem*var(--bs,1));color:var(--ink)}",
".rolltable .rtbar{display:flex;align-items:center;gap:12px}",
".rolltable .rtroll{font:inherit;font-size:.9rem;font-weight:600;background:var(--accent);color:#fff;border:none;border-radius:9px;padding:9px 18px;cursor:pointer}",
".rolltable .rtroll:hover{opacity:.92}",
".rolltable .rtresult{font-family:var(--mono);font-size:.78rem;color:var(--muted)}",
/* checklist */
".checklist{display:flex;flex-direction:column;gap:5px;margin:2px 0 8px}",
".checklist .ckhd{font-family:var(--mono);font-size:.6rem;letter-spacing:.06em;color:var(--faint);padding:0 2px 2px}",
".checklist .ckrow{display:grid;grid-template-columns:auto 1fr;gap:9px;align-items:baseline;border:1px solid var(--rule);border-radius:8px;background:var(--panel);padding:6px 11px}",
".checklist .ckbox{color:var(--muted);font-size:1.05rem;line-height:1}",
".checklist .ckrow.done .ckbox{color:var(--accent)}",
".checklist .cktext{font-size:calc(.98rem*var(--bs,1));color:var(--ink)}",
".checklist .ckrow.done .cktext{color:var(--muted);text-decoration:line-through}",
/* progress clocks */
".clocks{display:flex;flex-wrap:wrap;gap:16px;margin:4px 0 8px}",
".clocks .clk{display:flex;flex-direction:column;align-items:center;gap:5px;width:104px}",
".clocks .clkface{width:66px;height:66px}",
".clocks .seg{fill:var(--panel-2);stroke:var(--bg);stroke-width:1.3}",
".clocks .seg.fill{fill:var(--accent)}",
".clocks .clkring{fill:none;stroke:var(--rule);stroke-width:1.4}",
".clocks .clklbl{text-align:center;font-size:.85rem;color:var(--ink)}",
".clocks .clkctl{font-family:var(--mono);font-size:.64rem;color:var(--muted)}",
/* NPC roster */
".roster{display:flex;flex-direction:column;gap:10px;margin:2px 0 8px}",
".roster .npc{display:grid;grid-template-columns:52px 1fr;gap:12px;border:1px solid var(--rule);border-left:3px solid var(--rule);border-radius:11px;background:var(--panel);padding:11px}",
".roster .npc[data-disp=friendly]{border-left-color:#4aa579}",
".roster .npc[data-disp=neutral]{border-left-color:#6f8296}",
".roster .npc[data-disp=wary]{border-left-color:#c99a5a}",
".roster .npc[data-disp=hostile]{border-left-color:#c05348}",
".roster .nport{width:52px;height:52px;border-radius:9px;border:1px solid var(--rule);background:var(--panel-2) center/cover;display:flex;align-items:center;justify-content:center;font-family:var(--head);font-size:1.3rem;color:var(--faint)}",
".roster .nmain{min-width:0}",
".roster .ntop{display:flex;align-items:baseline;gap:9px;flex-wrap:wrap;margin-bottom:4px}",
".roster .nnm{font-family:var(--head);font-size:calc(1.1rem*var(--hs,1));color:var(--ink)}",
".roster .nrole{font-family:var(--mono);font-size:.54rem;letter-spacing:.06em;text-transform:uppercase;color:#6f8296}",
".roster .ndisp{font-family:var(--mono);font-size:.5rem;letter-spacing:.05em;text-transform:uppercase;color:var(--muted);border:1px solid var(--rule);border-radius:20px;padding:2px 8px}",
".roster .nrows{display:flex;flex-direction:column;gap:2px}",
".roster .nrow{display:flex;gap:8px;font-size:calc(.92rem*var(--bs,1))}",
".roster .nk{font-family:var(--mono);font-size:.48rem;letter-spacing:.06em;text-transform:uppercase;color:var(--faint);width:48px;flex:0 0 48px;text-align:right;padding-top:3px}",
".roster .nv{color:var(--ink)}",
/* plot twists */
".twists{display:flex;flex-direction:column;gap:10px;margin:2px 0 8px}",
".twist{border:1px solid var(--rule);border-left:3px solid var(--st,var(--rule));border-radius:11px;background:var(--panel);padding:11px 14px;display:flex;flex-direction:column;gap:7px}",
".twist.cut{opacity:.6}",
".twist .twtop{display:flex;align-items:baseline;gap:10px;flex-wrap:wrap}",
".twist .twnum{font-family:var(--mono);font-size:.6rem;color:var(--st,var(--faint));border:1px solid var(--st,var(--rule));border-radius:5px;padding:2px 6px;line-height:1;align-self:center}",
".twist .twhook{font-family:var(--head);font-size:calc(1.2rem*var(--hs,1));color:var(--ink);flex:1;min-width:0}",
".twist .twbadge{font-family:var(--mono);font-size:.52rem;letter-spacing:.1em;text-transform:uppercase;font-weight:600;border:1px solid var(--rule);border-radius:20px;padding:2px 9px;align-self:center}",
".twist .twface{display:flex;gap:9px;font-size:calc(.95rem*var(--bs,1))}",
".twist .twl{font-family:var(--mono);font-size:.5rem;letter-spacing:.08em;text-transform:uppercase;color:var(--faint);width:52px;flex:0 0 52px;text-align:right;padding-top:4px}",
".twist .twbody{font-size:calc(.95rem*var(--bs,1));line-height:1.55;color:var(--ink);white-space:pre-wrap}",
".twist .twhinge{font-family:var(--mono);font-size:.58rem;letter-spacing:.04em;color:var(--muted);margin-top:1px}",
/* avoid / anachronism variant */
".deflist.avoidlist{gap:7px}",
".deflist.avoidlist .drow{grid-template-columns:auto minmax(0,0.9fr) minmax(0,2fr);border:1px solid var(--rule);border-left:3px solid #c05348;border-radius:8px;background:var(--panel);padding:8px 13px}",
".deflist .dx{color:#c05348;font-weight:700}",
"@media(max-width:640px){.deflist.avoidlist .drow{grid-template-columns:auto 1fr}}",

/* chronology timeline */
".chron{position:relative;margin:4px 0 6px;padding-left:22px}",
".chron::before{content:'';position:absolute;left:4px;top:8px;bottom:8px;width:1px;background:var(--rule)}",
".chron .cnode{position:relative;padding:6px 0;display:flex;gap:12px;flex-wrap:wrap;align-items:baseline}",
".chron .cnode::before{content:'';position:absolute;left:-22px;top:12px;width:9px;height:9px;border-radius:50%;background:var(--panel);border:2px solid var(--accent)}",
".chron .cdate{font-family:var(--mono);font-size:.62rem;letter-spacing:.06em;color:var(--accent);white-space:nowrap}",
".chron .cev{color:var(--ink)}",
".chron .cev a{color:var(--accent);text-decoration:none}.chron .cev a:hover{text-decoration:underline}",

/* source notes — chapter spine + typed notes + plates */
".snbook{display:flex;flex-direction:column;gap:11px;margin:4px 0 6px}",
".snthemes{display:flex;flex-wrap:wrap;gap:7px;align-items:center;margin-bottom:4px}",
".snthemes .thlbl{font-family:var(--mono);font-size:.56rem;letter-spacing:.14em;text-transform:uppercase;color:var(--faint);margin-right:4px}",
".snthemes .thm{font-family:var(--mono);font-size:.6rem;color:var(--muted);border:1px solid var(--rule);border-radius:20px;padding:4px 10px}",
".snthemes .thm .c{color:var(--faint)}",
".snchap{border:1px solid var(--rule);border-radius:12px;background:var(--panel);overflow:hidden}",
".snchap>summary{list-style:none;cursor:pointer;display:grid;grid-template-columns:auto 1fr auto auto;gap:12px;align-items:center;padding:12px 15px}",
".snchap>summary::-webkit-details-marker{display:none}",
".snstate{width:11px;height:11px;border-radius:50%;border:1px solid var(--faint)}",
".snstate.now{background:var(--accent);border-color:var(--accent)}",
".snstate.done{background:#4aa579;border-color:#4aa579}",
".snchmid{min-width:0;display:flex;flex-direction:column;gap:2px}",
".snchtitle{font-family:var(--head);font-size:calc(1.2rem*var(--hs,1));color:var(--ink);line-height:1.15}",
".snchmid .chsum{font-family:var(--body);font-size:.92rem;color:var(--muted)}",
".snpp{font-family:var(--mono);font-size:.58rem;letter-spacing:.06em;text-transform:uppercase;color:var(--faint);white-space:nowrap}",
".snchn{font-family:var(--mono);font-size:.62rem;color:var(--muted);min-width:1.5em;text-align:right}",
".snnotes{border-top:1px solid var(--rule);padding:13px 15px;display:flex;flex-direction:column;gap:10px}",
".snnote{border:1px solid var(--rule);border-left:3px solid var(--nc,var(--rule));border-radius:9px;background:var(--panel-2);padding:10px 14px}",
".sntop{display:flex;align-items:baseline;gap:12px;margin-bottom:5px;flex-wrap:wrap}",
".sntype{font-family:var(--mono);font-size:.55rem;letter-spacing:.11em;text-transform:uppercase;color:var(--nc,var(--muted))}",
".sntags{margin-left:auto;display:flex;gap:6px;flex-wrap:wrap}",
".sntags span{font-family:var(--mono);font-size:.52rem;letter-spacing:.04em;color:var(--faint);border:1px solid var(--rule);border-radius:12px;padding:2px 8px}",
".snbody{font-size:calc(1rem*var(--bs,1));line-height:1.58;color:var(--ink)}",
".snbody p{margin:0 0 8px}.snbody p:last-child{margin:0}",
".snnote.type-quote .snbody{font-style:italic;color:var(--muted)}",
".snnote.type-summary .snbody{color:var(--muted)}",
".snnote .pcontent{margin-top:4px}",
".snnote.place-left .pcontent,.snnote.place-right .pcontent{display:grid;gap:16px;align-items:start}",
".snnote.place-left .pcontent{grid-template-columns:minmax(150px,42%) 1fr}",
".snnote.place-right .pcontent{grid-template-columns:1fr minmax(150px,42%)}",
".snnote.place-right .snfig{order:2}",
".sncap{font-size:.94rem;line-height:1.5;color:var(--muted);margin-top:8px}",
".sncap p{margin:0 0 6px}.sncap p:last-child{margin:0}",
".snnote.place-left .sncap,.snnote.place-right .sncap{margin-top:0}",
"@media(max-width:640px){.snnote.place-left .pcontent,.snnote.place-right .pcontent{grid-template-columns:1fr}.snnote.place-right .snfig{order:0}}",

/* references / bibliography */
".refs{list-style:none;margin:2px 0 6px;padding:0;display:flex;flex-direction:column;gap:8px}",
".refs .ref{display:flex;gap:12px;align-items:baseline;border:1px solid var(--rule);border-radius:10px;background:var(--panel);padding:10px 14px}",
".refs .rkind{flex:none;font-family:var(--mono);font-size:.54rem;letter-spacing:.1em;text-transform:uppercase;color:var(--accent-soft);border:1px solid var(--rule);border-radius:20px;padding:3px 9px}",
".refs .rbody{display:flex;flex-direction:column;gap:3px;min-width:0}",
".refs .rtop{display:flex;align-items:center;gap:10px;flex-wrap:wrap;font-family:var(--body);font-size:calc(.98rem*var(--bs,1));color:var(--ink)}",
".refs .rtop a{color:var(--accent);text-decoration:none}.refs .rtop a:hover{text-decoration:underline}",
".refs .rrel{display:inline-flex;gap:2px}",
".refs .rrel .pip{width:6px;height:6px;border-radius:50%;border:1px solid var(--accent-soft)}",
".refs .rrel .pip.on{background:var(--accent-soft)}",
".refs .rnote{font-family:var(--sans);font-size:.8rem;color:var(--muted)}",

/* real-vs-invented ledger */
".ledger{display:flex;flex-direction:column;gap:7px;margin:2px 0 6px}",
".ldrow{display:grid;grid-template-columns:minmax(0,1.3fr) auto minmax(0,1.5fr);gap:14px;align-items:baseline;border:1px solid var(--rule);border-left:3px solid var(--vc);border-radius:9px;background:var(--panel);padding:9px 14px}",
".ldclaim{font-family:var(--body);font-size:calc(.95rem*var(--bs,1));color:var(--ink)}",
".ldverd{font-family:var(--mono);font-size:.56rem;letter-spacing:.08em;text-transform:uppercase;color:var(--vc);justify-self:start;align-self:center}",
".ldnote{font-family:var(--sans);font-size:.8rem;color:var(--muted)}",
"@media(max-width:640px){.ldrow{grid-template-columns:1fr;gap:4px}.ldverd{justify-self:start}}",

/* excerpts */
".exc{border:1px solid var(--rule);border-radius:6px;background:var(--panel);margin-bottom:8px}",
".exc>summary{list-style:none;cursor:pointer;padding:10px 14px;font-family:var(--body);font-size:calc(.95rem*var(--bs,1));color:var(--ink);display:flex;gap:10px;align-items:center}.exc>summary::-webkit-details-marker{display:none}.exc>summary::before{content:'“';font-family:var(--head);font-size:1.3rem;color:var(--accent);line-height:0}",
".exc .eb{padding:0 16px 14px}.exc .src{font-family:var(--mono);font-size:.58rem;letter-spacing:.12em;text-transform:uppercase;color:var(--faint);margin-top:8px}",

/* outline */
".outline{display:flex;flex-direction:column;gap:10px}",
".act{border:1px solid var(--rule);border-radius:8px;background:var(--panel);padding:12px 14px}.act .at{font-family:var(--head);font-size:calc(1.2rem*var(--hs,1));color:var(--ink);margin-bottom:6px}",
".chap{border-left:2px solid var(--rule);margin:8px 0 8px 6px;padding-left:12px}.chap .ct{font-family:var(--mono);font-size:.6rem;letter-spacing:.1em;text-transform:uppercase;color:var(--accent);margin-bottom:4px}",
".beat{display:flex;gap:8px;font-family:var(--body);font-size:calc(.95rem*var(--bs,1));color:var(--ink);opacity:.92;margin:6px 0}.beat .dot{color:var(--accent-soft);flex:none;line-height:1.6}.beat .btext{flex:1;min-width:0}.beat .btext p{margin:0 0 .45em}.beat .btext p:last-child{margin-bottom:0}",

/* lineage */
".lineage{overflow-x:auto}.lcanvas{display:flex;gap:30px;justify-content:center;padding:8px 4px}",
".subtree{display:inline-flex;flex-direction:column;align-items:center}.union{display:flex;align-items:center}",
".lnode,.pnode{border:1px solid var(--rule);border-radius:7px;background:var(--panel);padding:6px 11px;font-family:var(--head);font-size:calc(.92rem*var(--hs,1));color:var(--ink);white-space:nowrap}.pnode{background:var(--panel-2)}",
".bond{display:flex;flex-direction:column;align-items:center;padding:0 3px}.bond .line{width:22px;height:2px;background:var(--accent-soft);border-radius:2px}.bond.affair .line{height:0;background:none;border-top:2px dashed var(--faint)}.bond .lbl{font-family:var(--mono);font-size:.42rem;text-transform:uppercase;color:var(--faint);margin-top:3px}",
".vline{width:1px;height:14px;background:var(--rule)}",
".kids{display:flex;gap:16px;align-items:flex-start;position:relative;padding-top:14px}.kids::before{content:'';position:absolute;top:0;left:12%;right:12%;height:1px;background:var(--rule)}.kids.single::before{display:none}",
".kids>.branch{position:relative}.kids>.branch::before{content:'';position:absolute;top:-14px;left:50%;width:1px;height:14px;background:var(--rule)}",

/* allegiance web */
".web{display:flex;flex-direction:column;align-items:center;padding:16px 8px;border:1px solid var(--rule);border-radius:10px;background:var(--panel)}",
".web .tier{display:flex;gap:10px;flex-wrap:wrap;justify-content:center}",
".web .box{border:1px solid var(--rule);border-radius:6px;padding:6px 13px;font-family:var(--head);font-size:calc(.9rem*var(--hs,1));color:var(--muted);background:var(--panel-2)}.web .box.self{border-color:var(--accent);color:var(--ink)}.web .box.liege{border-color:var(--accent-soft);color:var(--ink)}",
".web .down{width:1px;height:16px;background:var(--rule)}",
".web .sides{display:flex;gap:26px;margin-top:14px;padding-top:12px;border-top:1px solid var(--line);flex-wrap:wrap}.web .side{display:flex;align-items:center;gap:6px;flex-wrap:wrap}.web .slbl{font-family:var(--mono);font-size:.52rem;letter-spacing:.12em;text-transform:uppercase;color:var(--faint)}",
".wchip{border:1px solid var(--rule);border-radius:14px;padding:3px 10px;font-family:var(--body);font-size:.72rem;color:var(--muted)}.wchip.rival{color:var(--accent-soft)}",

/* event timeline */
".etl{border:1px solid var(--rule);border-radius:10px;background:var(--panel);padding:14px 12px;margin:6px 0}",
".track{position:relative;display:flex;gap:8px;overflow-x:auto;padding:6px 4px}.track .line{position:absolute;left:8px;right:8px;top:50%;height:2px;background:var(--rule)}",
".enode{position:relative;z-index:1;display:flex;flex-direction:column;align-items:center;gap:6px;min-width:100px;text-decoration:none}",
".enode .date{font-family:var(--mono);font-size:.54rem;letter-spacing:.06em;text-transform:uppercase;color:var(--faint);white-space:nowrap}",
".enode .edot{width:12px;height:12px;border-radius:50%;background:var(--panel-2);border:2px solid var(--rule)}.enode.current .edot{background:var(--accent);border-color:var(--accent)}",
".enode .ettl{font-family:var(--body);font-size:.78rem;color:var(--muted);text-align:center;max-width:120px}.enode.current .ettl{color:var(--ink)}",

/* hub + index pages */
".hubwrap{max-width:1180px;margin:0 auto;padding:44px 26px 90px}",
".hhero{margin-bottom:30px;padding-bottom:20px;border-bottom:1px solid var(--rule)}",
".hhero .eyebrow{font-family:var(--mono);font-size:.64rem;letter-spacing:.32em;text-transform:uppercase;color:var(--accent);margin:0 0 10px}",
".hhero h1{font-family:var(--head);font-weight:400;font-size:calc(clamp(2rem,5vw,3.2rem)*var(--hs,1));line-height:1;margin:0}",
".hhero .hcount{font-family:var(--mono);font-size:.7rem;letter-spacing:.12em;text-transform:uppercase;color:var(--muted);margin-top:11px}",
".hup{display:inline-block;font-family:var(--mono);font-size:.62rem;letter-spacing:.14em;text-transform:uppercase;color:var(--muted);margin-bottom:14px}.hup:hover{color:var(--ink);text-decoration:none}",
".hsec{margin:30px 0}.hsec h2{display:flex;align-items:center;gap:10px}.hsec .hic{color:var(--accent-soft)}",
".hgrid{display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:16px}",
".ecard{position:relative;background:var(--panel);border:1px solid var(--rule);border-radius:14px;overflow:hidden;transition:transform .12s,border-color .12s}.ecard:hover{transform:translateY(-3px);border-color:var(--accent);text-decoration:none}",
".ecard .portrait{aspect-ratio:3/4;background:var(--panel-2) center/cover;position:relative;display:flex;align-items:center;justify-content:center}",
".ecard .portrait::after{content:'';position:absolute;inset:0;background:linear-gradient(180deg,transparent 45%,rgba(0,0,0,.72))}",
".ecard .ini{font-family:var(--head);font-size:2.6rem;color:var(--line);text-transform:uppercase}",
".ecard .cmeta{position:absolute;left:0;right:0;bottom:0;z-index:2;padding:12px 13px}",
".ecard .cnm{font-family:var(--head);font-size:calc(1.2rem*var(--hs,1));line-height:1.05;color:#fff}",
".ecard .csub{font-family:var(--mono);font-size:.54rem;letter-spacing:.14em;text-transform:uppercase;color:var(--accent-soft);margin-top:5px}",
".pgrid{display:grid;grid-template-columns:repeat(auto-fill,minmax(300px,1fr));gap:20px}",
".pcard{background:var(--panel);border:1px solid var(--rule);border-radius:16px;overflow:hidden;transition:transform .12s,border-color .12s;display:block}.pcard:hover{transform:translateY(-3px);border-color:var(--accent);text-decoration:none}",
".phero{position:relative;aspect-ratio:4/3;background:var(--panel-2) center/cover;display:flex;align-items:center;justify-content:center;border-bottom:1px solid var(--rule)}",
".phero::after{content:'';position:absolute;inset:0;background:linear-gradient(180deg,transparent 55%,rgba(0,0,0,.5))}",
".pini{font-family:var(--head);font-size:3.4rem;color:var(--line);text-transform:uppercase}",
".pcard .pbody{padding:15px 17px 17px}.pcard .pt{font-family:var(--head);font-size:calc(1.5rem*var(--hs,1));line-height:1.08;color:var(--ink)}",
".pcard .pmeta{font-family:var(--mono);font-size:.58rem;letter-spacing:.12em;text-transform:uppercase;color:var(--accent-soft);margin-top:8px}",

/* linked from (backlinks) */
".blh{margin-top:34px}",
".bllist{list-style:none;padding:0;margin:6px 0 0;display:flex;flex-direction:column;gap:8px}",
".bl{display:flex;align-items:center;gap:12px;border:1px solid var(--rule);border-radius:10px;background:var(--panel);padding:10px 14px}",
".bl .blic{color:var(--accent-soft);flex:none;width:1.2em;text-align:center}",
".bl .blnm{font-family:var(--head);font-size:calc(1.1rem*var(--hs,1));color:var(--ink)}",
".bl .blnm a{color:var(--ink)}.bl .blnm a:hover{color:var(--accent)}",
".bl .blmeta{margin-left:auto;font-family:var(--mono);font-size:.56rem;letter-spacing:.14em;text-transform:uppercase;color:var(--muted);text-align:right}",

/* site shell + sidebar nav */
".shell{display:grid;grid-template-columns:250px minmax(0,1fr);align-items:start}",
".content{min-width:0}",
".sidenav{position:sticky;top:0;height:100vh;overflow-y:auto;background:var(--panel-2);border-right:1px solid var(--rule)}",
".navhead{padding:16px 16px 12px;border-bottom:1px solid var(--rule);position:sticky;top:0;background:var(--panel-2);z-index:1}",
".nhub{font-family:var(--head);font-size:1.1rem;color:var(--ink)}",
"a.nhub:hover{color:var(--accent);text-decoration:none}.nhub.cur{color:var(--accent)}",
".navtree{padding:8px 8px 60px}",
".nfamh{font-family:var(--mono);font-size:.54rem;letter-spacing:.2em;text-transform:uppercase;color:var(--faint);padding:12px 8px 4px}",
".ntype>summary{list-style:none;cursor:pointer;display:flex;align-items:center;gap:8px;padding:6px 8px;border-radius:7px;font-family:var(--mono);font-size:.68rem;letter-spacing:.05em;color:var(--muted)}",
".ntype>summary::-webkit-details-marker{display:none}",
".ntype>summary:hover{color:var(--ink);background:var(--panel)}",
".ntype .nic{color:var(--accent-soft)}.ntype .nlbl{flex:1}.ntype .nct{color:var(--faint);font-size:.62rem}",
".ntype ul{list-style:none;margin:0 0 6px;padding:2px 0 2px 6px}",
".ntype li a,.ntype li span{display:block;padding:5px 10px;border-radius:6px;font-family:var(--body);font-size:.92rem;color:var(--muted);border-left:2px solid transparent;line-height:1.3}",
".ntype li a:hover{color:var(--ink);background:var(--panel);text-decoration:none}",
".ntype li.cur span{color:var(--accent);border-left-color:var(--accent);background:var(--panel)}",
".navtoggle{display:none;background:none;border:1px solid var(--rule);border-radius:6px;color:var(--muted);cursor:pointer;padding:3px 9px;font-size:.95rem;line-height:1}",
".content>.navtoggle{margin:12px 0 0 18px}",
".navtoggle:hover{border-color:var(--accent);color:var(--ink)}",
".navback{display:none}",

/* responsive */
"@media(max-width:860px){.wsplit{grid-template-columns:1fr;gap:22px}.wsplit .media{position:static}.wbody{grid-template-columns:1fr;gap:10px}}",
"@media(max-width:860px){.shell{display:block}.sidenav{position:fixed;top:0;left:0;bottom:0;width:min(280px,82vw);z-index:60;transform:translateX(-100%);transition:transform .22s ease;box-shadow:0 0 40px rgba(0,0,0,.5)}.shell.nav-open .sidenav{transform:none}.navtoggle{display:inline-flex;align-items:center}.shell.nav-open .navback{display:block;position:fixed;inset:0;background:rgba(0,0,0,.5);z-index:55;border:none}}"
].join("\n");
